version: '3'
services:
  datadog-agent:
    image: "datadog/agent:6.5.2"
    environment:
      - DD_API_KEY
      - DD_APM_ENABLED=true
    ports:
      - "8126:8126"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
  noder:
    build: .
    command: nodemon test.js
    ports:
      - "9001:9001"
    volumes:
      - ".:/app"
    depends_on:
      - datadog-agent